/** GET CATEGORY API */
export const GET_CATEGORY_PROGRESS = "GET_CATEGORY_PROGRESS";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_ERROR = "GET_CATEGORY_ERROR";

/** POST CATEGORY API */
export const POST_CATEGORY_PROGRESS = "POST_CATEGORY_PROGRESS";
export const POST_CATEGORY_SUCCESS = "POST_CATEGORY_SUCCESS";
export const POST_CATEGORY_ERROR = "POST_CATEGORY_ERROR";